# FROM node:18-alpine As ui-build
# WORKDIR /usr/src/app
# COPY client/ ./client/
# RUN cd client && npm install && npm run build




# FROM node:18-alpine As development
# # Create app directory
# WORKDIR /usr/src/app

# # Copy application dependency manifests to the container image.
# # A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
# # Copying this first prevents re-running npm install on every code change.
# COPY --chown=node:node package*.json ./
# COPY --chown=node:node --from=ui-build /usr/src/app/client/build ./client/build
# # Install app dependencies using `npm install`
# RUN npm install

# # Bundle app source
# COPY --chown=node:node . .


# EXPOSE 4000
# CMD [ "npm", "start" ]


FROM node:14-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

WORKDIR /app/client
RUN npm install
RUN npm run build

WORKDIR /app
EXPOSE 4000
CMD ["npm", "start"]